runtime: java21
instance_class: F1
entrypoint: java -jar target/DRCarsApiREST-0.0.1-SNAPSHOT.jar

automatic_scaling:
  min_instances: 1
  max_instances: 2
 
env_variables:
  GCLOUD_STORAGE_BUCKET: drcars-tfg-project-bucket