version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-drcars
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: drcars
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  drcars-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drcars-api
    depends_on:
      - db
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_NAME: DRCarsApiREST
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/drcars?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SERVER_PORT: 9090

volumes:
  mysql_data:
